### ISSUE TITLE
File Name

### ISSUE THREAD

**Issue by dretax** [Ale46/Mega-Java#6]
Nope, File name is now something else.

What I got is: eA9f-fMYfFaNpVbchl44bwRcbfBU

I will stick to the filecreating and split method for now, and once you fixed It I will do a pull request about an idea.

Two methods are missing try catches or throws Exception. I also showed that in the pull request.

**Comment by Ale46** [comment]
Can you please give me the mega.co.nz link to download the file that give
this problem?

2015-04-25 21:03 GMT+02:00 dretax <notifications@github.com>:

**Comment by dretax** [comment]
Here

https://mega.co.nz/#!uNhA2KBZ!160OJT6EaRiBAftw6qS2slSo7zMEIfyUOrU9SBigo7U

**Comment by Ale46** [comment]
It seems that the response come with a json that is formatted in different ways.
With your file I was getting: 
```json
{"c":"SOMETHING","n":"FILENAME"}
```
Using a file from my account I was getting:
```json
{"n":"FILENAME","c":"SOMETHING"}
```
So your code was failing with my file, and my code was failing with yours. Now all should be ok.

**Comment by dretax** [comment]
Interesting. I remember I got "c" thing with another file too. xD
